-- JOM BACA: UNIQUE ONE-TIME UNLOCK CODE
-- Run semua SQL ini dalam Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.unlock_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  used boolean not null default false,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.unlock_codes enable row level security;

-- Jangan benarkan browser baca / edit table secara terus.
revoke all on table public.unlock_codes from anon, authenticated;

-- RPC ini atomik: hanya satu request boleh berjaya redeem code yang sama.
create or replace function public.redeem_unlock_code(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
  v_exists boolean;
begin
  update public.unlock_codes
     set used = true,
         used_at = now()
   where upper(code) = upper(trim(p_code))
     and used = false
  returning id into v_id;

  if v_id is not null then
    return jsonb_build_object('success', true, 'reason', 'redeemed');
  end if;

  select exists(
    select 1
      from public.unlock_codes
     where upper(code) = upper(trim(p_code))
       and used = true
  ) into v_exists;

  if v_exists then
    return jsonb_build_object('success', false, 'reason', 'used');
  end if;

  return jsonb_build_object('success', false, 'reason', 'invalid');
end;
$$;

revoke all on function public.redeem_unlock_code(text) from public;
grant execute on function public.redeem_unlock_code(text) to anon;

-- Helper untuk generate code. Guna dalam SQL Editor sahaja.
create or replace function public.generate_unlock_codes(p_count integer default 20)
returns table(code text)
language plpgsql
security definer
set search_path = public
as $$
declare
  i integer;
  v_code text;
begin
  if p_count < 1 or p_count > 500 then
    raise exception 'p_count mesti antara 1 dan 500';
  end if;

  for i in 1..p_count loop
    loop
      v_code := 'JB-' ||
                upper(substr(encode(gen_random_bytes(4), 'hex'), 1, 4)) ||
                '-' ||
                upper(substr(encode(gen_random_bytes(4), 'hex'), 1, 4));
      begin
        insert into public.unlock_codes(code) values (v_code);
        exit;
      exception when unique_violation then
        -- cuba code lain
      end;
    end loop;

    code := v_code;
    return next;
  end loop;
end;
$$;

-- Jangan expose generator kepada browser.
revoke all on function public.generate_unlock_codes(integer) from public, anon, authenticated;

-- Contoh selepas setup:
-- select * from public.generate_unlock_codes(20);
--
-- Semak code:
-- select code, used, used_at, created_at
-- from public.unlock_codes
-- order by id desc;
